config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  root 'teachers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :name, presence: true
  validates :school, presence: true
  validates :year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update(teacher_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    redirect_to root_path
  end

  private
    def teacher_params
      params.require(:teacher).permit(:name, :school, :year)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTeacherApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/teachers/edit.html.haml
.container
  .row.justify-content-md-center
    %h1 Edit Teacher
    %a.btn.btn-primary{href: "/teachers/", style: "float:right"} Teachers Index
  %br
  .row
  = form_for @teacher do |f|
    .card
      .card-body
        .mb-3
          = f.label :name, { class: "form-label"}
          = f.text_field :name, { class: "form-control", placeholder: "Name" }
        %br
        .mb-3
          = f.label :school, { class: "form-label"}
          = f.text_field :school, { class: "form-control", placeholder: "School" }
        %br
        .mb-3
          = f.label :year, { class: "form-label"}
          = f.text_field :year, { class: "form-control", placeholder: "Year" }
        %br
        = f.submit "Submit", class: "btn btn-primary"

app/views/teachers/index.html.haml
.container
  .row.justify-content-md-center
    %h1 Teachers Index
  .row
    .col-lg-6
      %p This will be a paginated/sortable table... I hope.
    .col-lg-offset-10
      %a.btn.btn-primary{href: "/teachers/new"} Create New Teacher

  .row
    .table-responsive
      %table.table.table-striped
        %thead
          %tr
            %th{width: '10%'} ID
            %th{width: '30%'} Name
            %th{width: '30%'} School
            %th{width: '10%'} Year
            %th{width: '10%'} Actions

        %tbody
          - @teachers.each do |teacher|
            %tr
              %td= teacher.id
              %td= teacher.name
              %td= teacher.school
              %td= teacher.year
              %td
                =button_to edit_teacher_path(teacher.id), method: :get, style: "float: left; margin-right:0.5em;", class: "btn btn-sm btn-info" do
                  %i.glyphicon.glyphicon-pencil
                =button_to teacher_path(teacher.id), method: :delete, class: "btn btn-sm btn-danger" do
                  %i.glyphicon.glyphicon-remove

app/views/teachers/new.html.haml
.container
  .row.justify-content-md-center
    %h1 Create A Teacher
    %a.btn.btn-primary{href: "/teachers/"} Teachers Index
  %br
  .row
  = form_for @teacher do |f|
    .card
      .card-body
        .mb-3
          = f.label :name, { class: "form-label"}
          = f.text_field :name, { class: "form-control", placeholder: "Name" }
        %br
        .mb-3
          = f.label :school, { class: "form-label"}
          = f.text_field :school, { class: "form-control", placeholder: "School" }
        %br
        .mb-3
          = f.label :year, { class: "form-label"}
          = f.text_field :year, { class: "form-control", placeholder: "Year" }
        %br
        = f.submit "Submit", class: "btn btn-primary"